apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: etcd
  namespace: openshift-logging
  labels:
    app: etcd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      generateName: etcd
      namespace: openshift-logging
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        ports:
        - containerPort: 4001
          name: client
        - containerPort: 7001
          name: peer
        command:
        - "sleep"
        - "1000000"
