apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: openshift-logging
  labels:
    name: etcd
spec:
  containers:
  - name: etcd
    image: quay.io/coreos/etcd:latest
    ports:
    - containerPort: 4001
      name: client
    - containerPort: 7001
      name: peer
    command:
    - "sleep"
    - "1000000"
