apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: openshift-logging
  labels:
    name: etcd
spec:
  containers:
  - name: etcd
    image: quay.io/coreos/etcd:latest
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: peer