apiVersion: v1
kind: Pod
metadata:
  name: rell
  namespace: openshift-logging
  labels:
    name: rell
spec:
  containers:
  - name: rell
    image: docker.io/vladmasarik/hackfest-dep
    command: ["sleep", "100000"]