
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: openshift-logging
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: docker.io/library/redis:latest
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
