apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: esrally
  namespace: openshift-logging
  annotations:
    openshift.io/display-name: EsRally
spec:
  dockerImageRepository: <docker-image-placeholder>
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      from:
        kind: DockerImage 
        name: <docker-image-placeholder>:latest
      importPolicy: {}
      name: "latest"
      referencePolicy:
        type: Local
