apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: esrally
  namespace: openshift-logging
  annotations:
    openshift.io/display-name: EsRally
spec:
  dockerImageRepository: docker.io/vladmasarik/hackfest-dep
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      from:
        kind: DockerImage 
        name: docker.io/vladmasarik/hackfest-dep:latest
      importPolicy: {}
      name: "latest"
      referencePolicy:
        type: Local
