apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
  labels:
    app: grafana-logging
  name: grafana-logging
  namespace: openshift-monitoring
spec:
  ports:
  - name: https
    port: 3000
    targetPort: https
  selector:
    app: grafana-logging
  type: ClusterIP


